### ISSUE TITLE
Aircraft database

### ISSUE THREAD

**Issue by BillDunn** [jontio/JAERO#15]
v1.0.4.5 When trying to download aircraft database from junzisun.com it's looking to download aircrafts_dump.csv from 

(http://junzisun.com/adb/download) and should download and convert aircraft_db.csv from (https://junzisun.com/adb/download). I tried 

to change to https: but get "error creating SSL context ()". Tried to merge .csv into database and got many errors.

**Comment by jontio** [comment]
I haven't implemented any SSL support so that you get an SSL error is expected.

Just now I tried downloading the database from http://junzisun.com/adb/download and the non-SSL connection works for me. Why do you want to download the database over SSL? Doesn't the non-SSL connection work for you?

**Comment by jontio** [comment]
Oh I just realised that what is returned with the non-SSL connect is a link to the SSL connection. I see the problem. I'll have a look at implementing SSL support.

**Comment by BillDunn** [comment]
Thx for getting back so quick Jonti. The problem I saw was when I used the
non-SSL default it downloads a 1K file "aircrafts_dump.csv" that is
imported to the aircrafts_dump.db file. If you open that up Junzi Sun has
the following info inside:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://junzisun.com/adb/download
">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at junzisun.com Port 80</address>
</body></html>

That's why I decided to try the secure link. If you go to his site (your
link) and manually press the download button you get a file called
"aircraft_db.csv" 5,918KB which now contains the aircraft database. I hope
I explained this well enough.

Thanks so much,
Bill Dunn
Dunnsville, Va. USA

**Comment by jontio** [comment]
I tried using the https address on my setup just now and I don't get the "error creating SSL context ()" you got. My installation has access to all the Qt libraries so it might just be that a DLL or two is needed to enable SSL support. It looks like it should be easy to fix. I'll let you know when I've fixed the problem.

**Comment by BillDunn** [comment]
That's certainly good news. I don't know if it will make any difference but
I did notice that the new csv file structure had different column titles
than your .db as I tried to import the new file into the .db file that was
created. Hopefully it won't mess with your import routine.

Bill

**Comment by jontio** [comment]
Thanks for noticing the csv structure change. I'll have to change the importing routine too; bother.

**Comment by jontio** [comment]
I've fond the missing files, they are libeay32.dll and ssleay32.dll . Don't see any format change of the csv file since Feb 2016. the format is still..

icao,regid,mdl,type,operator
000334,PU-PLS,ULAC,EDRA SUPER PETREL LS,PRIVATE OWNER

so I think all is required are these two files.

**Comment by BillDunn** [comment]
Thx Jonti, I just got those dll's from Thibaut 'Fouine' as we've been
discussing this on the SDRplay FaceBook group.

Bill

**Comment by jontio** [comment]
I've now released the update with the SSL DLLs in the Windows binary package. The URL should also automatically change to https://junzisun.com/adb/download if JAERO sees the URL pointing to http://junzisun.com/adb/download

Cheers,
Jonti

**Comment by BillDunn** [comment]
Thanks Jonti,
It's working great. Just started with your program on L-band this week and
I'm already looking to try C-band. Just need to make a C-band antenna.

Bill

**Comment by BillDunn** [comment]
Jonti,

One more question if I may. I have added a MIL aircraft database to the
aircrafts_dump.csv file. Is there any way I can tell JAERO to convert that
file to a new aircrafts_dump.db file? I have tried putting this in the URL
line for database link but it does not pick up the file.  http://
192.168.0.246/C:/A_MIL_List/aircrafts_dump.csv  My expertise in creating a
webpage that would recreate the "download" function is somewhat lacking so
I am looking for an easier workaround or solution.

Thanks so much
Wm Dunn

**Comment by jontio** [comment]
Hi Bill,

I cant entirely remember but I think that might be possible if you rename the file you want to import
to "new.aircrafts_dump.csv" and place it in the database directory. I had a feeling that when JAERO first started it looked for a file of that name.

Cheers,
Jonti

**Comment by BillDunn** [comment]
Jonti,

Once again you're the man, that works.

Thanks,
Bill

**Comment by jontio** [comment]
The database download had to be fixed again. The file is now compressed with GZIP. So I've yet again fixed it. I haven't bothered releasing a new update for such a tiny thing but instead just replaced the the binaries. Not quiet correct but good enough. You'll only need the new binaries when you want to download the database again.

**Comment by BillDunn** [comment]
Thx Jonti, seems like the database site is keeping you busy making changes
to your import routine. :-)  I don't know if you're open to any other
changes but it would be nice if it auto populated the aircraft rec'd with
the database information without having to manually clicking on each entry
as finding out the details of each aircraft is a major piece of information
when using JAERO.

Again, thank's for a great program.

Bill

**Comment by jontio** [comment]
Hi Bill,

Yes. I'm not sure why he keeps changing the format all the time; not exactly a good use of my time.

In retrospect I shouldn't have made it so you needed to click on each plane for the database to populate the info cells but at the time I thought that would be a good idea as any plane unpopulated you would know was a plane that you hadn't seen before. However I'm unlikely to change it due to the amount of time it would take to figure out how it all works again; I'm still hoping someone else looks for it and will change it.

Cheers,
Jonti

**Comment by BillDunn** [comment]
Jonti,

You can be satisfied in the fact that you spearheaded the program in the
1st place. I believe Jeroen Beijer has been discussing with you as to
adding some additional burst rate decoding to JAERO and maybe he can
continue your work as you move on to other things. You have obviously spent
countless hours in getting it to the point it is now. :-)

Thanks
Bill

**Comment by jontio** [comment]
Hi Bill,

Thanks.

Yes Jeroen has been looking into 1200 bps bursts. He has found them and taken a recording of them. It would be nice if he could add 1200 bps burst support. His current challenge is to identify the packets both in time and in frequency (a 2D search problem) really fast. I've suggested he use Octave or Matlab to test ideas and see what works best. I found this 2D search problem difficult. If he manages to do it, then after that it's fairly easy.

Cheers,
Jonti

**Comment by jontio** [comment]
done

**Comment by kyanhluong** [comment]
> Hi Bill,
> 
> I cant entirely remember but I think that might be possible if you rename the file you want to import
> to "new.aircrafts_dump.csv" and place it in the database directory. I had a feeling that when JAERO first started it looked for a file of that name.
> 
> Cheers,
> Jonti

Yes, rename file work in my case here
