### ISSUE TITLE
Add duplicate "output to udp" to support multiple programs

### ISSUE THREAD

**Issue by jontio** [jontio/JAERO#31]
Currently only one output is available for outputting ACARS data to UDP. If multiple programs are wanting the data there will be a problem if they aren't all using SO_REUSEADDR when binding to the UDP port. adding two ports containing the same data would allow two programs to receive the data.

**Comment by DickvanNoort** [comment]
Hi Jontio,  if you or anyone else implements this feature please add not just additional ports on the same host but multiple <host:port> destinations. 
Also very usefull for testing.

**Comment by jontio** [comment]
I've changed it now you can use multiple udp ports for the ACARS data. I've pushed it to master https://github.com/jontio/JAERO/commit/c4524f277118ea76979201c73e843297ea1143c9 but not made a released yet. To use it you type some thing like "localhost:12345 localhost:12346 localhost:123457" etc. Just put a space between them.

**Comment by DickvanNoort** [comment]
Thank you very much.  
Sofar I have only used it on Windows and not on Linux (my RPI's) and as I don't know how to compile it for Windows, I will wait untill a compiled (Windows) version is available.

**Comment by jontio** [comment]
I've now done the release at https://github.com/jontio/JAERO/releases/tag/v1.0.4.11 and added some Windows binaries of it to the release.
