### ISSUE TITLE
Compiling for 32 Bit But No Audio

### ISSUE THREAD

**Issue by KR0SIV** [jontio/JAERO#33]
I've compiled JAERO using msys2 (mingw-32) and QT Creator.

I manually compiled each dependency using mingw-32 including mbelib/aeroambe.
The software did compile and it locks signals just fine, it displays it has data and it logs to disk .ogg files but no audio is ever recovered.

I should also note that JAERO doesn't give an error when loading the aeroambe.dll

When I compile using QT Creator for JAERO I get the following

![ERROR](https://i.imgur.com/cCXryxf.png)

The compiling of each dependency seems to be fine and I'm not sure where I went wrong.

I'm planning to use the software on a dedicated pc which unfortunately is x86 only.

Thank you for all your time and support. I hope you have a moment to help me, I've spent two weeks trying to figure out how to compile this stuff on windows and it's been a heck of a learning experience.

**Comment by jontio** [comment]
The audio goes to the default audio output device. Have you set your default audio output device to something that is different than the output device from your SDR application?

My guess is that you have compiled it all correctly. There's always a few warnings, these shouldn't be a problem but someone should probably go through and fix them up sometime just to be sure.

The default output audio device is chosen by `audio_device_out=QAudioDeviceInfo::defaultOutputDevice();` in https://github.com/jontio/JAERO/blob/master/JAERO/audiooutdevice.h .

`qint64 AudioOutDevice::readData(char *data, qint64 maxlen)` in https://github.com/jontio/JAERO/blob/master/JAERO/audiooutdevice.cpp is what supplies the soundcard with audio so if you replace that with something that puts random values into `data` you should hear white noise. you could also use a `qDebug()<<".";` line in that function to show you that it is actually being called if you still get no sound out.

As far as I know it's only been tested on Windows 7 and up on Windows machines. So if you are using Windows XP that potentially could be a problem.

However, my guess is you have your default audio output device set to the same device as the output from your SDR application.

**Comment by KR0SIV** [comment]
Thanks for the pointers I'll give the debug stuff a try.
I could only wish that it were a default audio device issue but I had tested that early on by simply running the x64 version alongside mine and instantly heard audio so the sound interface is correct.

I have SDR# playing an iq in a loop feeding a virtual audio cable, that audio cable then ran to both my build and your build to test audio.

I'm compiling this on an x64 windows 7 machine using the MSYS/mingw32 and QT mingw32 kit

**Comment by KR0SIV** [comment]
I'm beginning to think the issue is coming from the aeroambe library although that compiled without error.
The reason I'm thinking this is that my build sometimes crashes but it seems only when areoambe.dll is in the directory.

Here is the dump, I can't really make much sense of it.

`
Dump Summary
------------
Dump File:	WER40B9.tmp.mdmp : C:\Users\Harold\AppData\Local\Temp\WER40B9.tmp.mdmp
Last Write Time:	12/4/2018 6:20:55 PM
Process Name:	JAERO.exe : C:\dev\jaero\JAERO-master\JAERO\release\JAERO.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.1.7601
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
JAERO.exe	C:\dev\jaero\JAERO-master\JAERO\release\JAERO.exe	0.0.0.0
ntdll.dll	C:\Windows\SysWOW64\ntdll.dll	6.1.7601.24291
kernel32.dll	C:\Windows\SysWOW64\kernel32.dll	6.1.7601.24291
KERNELBASE.dll	C:\Windows\SysWOW64\KERNELBASE.dll	6.1.7601.24291
libcorrect.dll	C:\dev\jaero\JAERO-master\JAERO\release\libcorrect.dll	0.0.0.0
msvcrt.dll	C:\Windows\SysWOW64\msvcrt.dll	7.0.7601.17744
libgcc_s_dw2-1.dll	C:\dev\jaero\JAERO-master\JAERO\release\libgcc_s_dw2-1.dll	0.0.0.0
libwinpthread-1.dll	C:\dev\jaero\JAERO-master\JAERO\release\libwinpthread-1.dll	1.0.0.0
libogg-0.dll	C:\dev\jaero\JAERO-master\JAERO\release\libogg-0.dll	0.0.0.0
libvorbis-0.dll	C:\dev\jaero\JAERO-master\JAERO\release\libvorbis-0.dll	0.0.0.0
libvorbisenc-2.dll	C:\dev\jaero\JAERO-master\JAERO\release\libvorbisenc-2.dll	0.0.0.0
Qt5Core.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Core.dll	5.11.2.0
advapi32.dll	C:\Windows\SysWOW64\advapi32.dll	6.1.7601.24291
sechost.dll	C:\Windows\SysWOW64\sechost.dll	6.1.7601.18869
rpcrt4.dll	C:\Windows\SysWOW64\rpcrt4.dll	6.1.7601.24291
sspicli.dll	C:\Windows\SysWOW64\sspicli.dll	6.1.7601.24291
CRYPTBASE.dll	C:\Windows\SysWOW64\CRYPTBASE.dll	6.1.7601.24291
mpr.dll	C:\Windows\System32\mpr.dll	6.1.7600.16385
netapi32.dll	C:\Windows\System32\netapi32.dll	6.1.7601.17887
netutils.dll	C:\Windows\System32\netutils.dll	6.1.7601.17514
srvcli.dll	C:\Windows\System32\srvcli.dll	6.1.7601.17514
wkscli.dll	C:\Windows\System32\wkscli.dll	6.1.7601.17514
ole32.dll	C:\Windows\SysWOW64\ole32.dll	6.1.7601.24291
gdi32.dll	C:\Windows\SysWOW64\gdi32.dll	6.1.7601.24260
user32.dll	C:\Windows\SysWOW64\user32.dll	6.1.7601.23594
lpk.dll	C:\Windows\SysWOW64\lpk.dll	6.1.7601.24231
usp10.dll	C:\Windows\SysWOW64\usp10.dll	1.626.7601.23894
shell32.dll	C:\Windows\SysWOW64\shell32.dll	6.1.7601.24234
shlwapi.dll	C:\Windows\SysWOW64\shlwapi.dll	6.1.7601.17514
userenv.dll	C:\Windows\SysWOW64\userenv.dll	6.1.7601.17514
profapi.dll	C:\Windows\SysWOW64\profapi.dll	6.1.7600.16385
version.dll	C:\Windows\System32\version.dll	6.1.7600.16385
winmm.dll	C:\Windows\System32\winmm.dll	6.1.7601.17514
ws2_32.dll	C:\Windows\SysWOW64\ws2_32.dll	6.1.7601.23451
nsi.dll	C:\Windows\SysWOW64\nsi.dll	6.1.7601.23889
libstdc++-6.dll	C:\dev\jaero\JAERO-master\JAERO\release\libstdc++-6.dll	0.0.0.0
Qt5Gui.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Gui.dll	5.11.2.0
Qt5Multimedia.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Multimedia.dll	5.11.2.0
Qt5Network.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Network.dll	5.11.2.0
crypt32.dll	C:\Windows\SysWOW64\crypt32.dll	6.1.7601.23971
msasn1.dll	C:\Windows\SysWOW64\msasn1.dll	6.1.7601.17514
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.1.7601.24168
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.1.7601.17514
winnsi.dll	C:\Windows\System32\winnsi.dll	6.1.7601.23889
Qt5PrintSupport.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5PrintSupport.dll	5.11.2.0
comdlg32.dll	C:\Windows\SysWOW64\comdlg32.dll	6.1.7601.17514
comctl32.dll	C:\Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.18837_none_ec86b8d6858ec0bc\comctl32.dll	5.82.7601.18837
winspool.drv	C:\Windows\System32\winspool.drv	6.1.7601.17514
Qt5Widgets.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Widgets.dll	5.11.2.0
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.1.7601.18917
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.1.7600.16385
Qt5Sql.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Sql.dll	5.11.2.0
imm32.dll	C:\Windows\System32\imm32.dll	6.1.7601.17514
msctf.dll	C:\Windows\SysWOW64\msctf.dll	6.1.7601.23915
qwindows.dll	C:\dev\jaero\JAERO-master\JAERO\release\platforms\qwindows.dll	5.11.2.0
oleaut32.dll	C:\Windows\SysWOW64\oleaut32.dll	6.1.7601.24117
qwindowsvistastyle.dll	C:\dev\jaero\JAERO-master\JAERO\release\styles\qwindowsvistastyle.dll	5.11.2.0
qtaudio_windows.dll	C:\dev\jaero\JAERO-master\JAERO\release\audio\qtaudio_windows.dll	5.11.2.0
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.1.7601.17514
propsys.dll	C:\Windows\System32\propsys.dll	7.0.7601.17514
wdmaud.drv	C:\Windows\System32\wdmaud.drv	6.1.7601.17514
ksuser.dll	C:\Windows\System32\ksuser.dll	6.1.7601.19091
avrt.dll	C:\Windows\System32\avrt.dll	6.1.7600.16385
setupapi.dll	C:\Windows\SysWOW64\setupapi.dll	6.1.7601.17514
cfgmgr32.dll	C:\Windows\SysWOW64\cfgmgr32.dll	6.1.7601.17621
devobj.dll	C:\Windows\SysWOW64\devobj.dll	6.1.7601.17621
AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.1.7601.23471
msacm32.drv	C:\Windows\System32\msacm32.drv	6.1.7600.16385
msacm32.dll	C:\Windows\System32\msacm32.dll	6.1.7600.16385
midimap.dll	C:\Windows\System32\midimap.dll	6.1.7600.16385
qsvgicon.dll	C:\dev\jaero\JAERO-master\JAERO\release\iconengines\qsvgicon.dll	5.11.2.0
Qt5Svg.dll	C:\dev\jaero\JAERO-master\JAERO\release\Qt5Svg.dll	5.11.2.0
qgif.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qgif.dll	5.11.2.0
qicns.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qicns.dll	5.11.2.0
qico.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qico.dll	5.11.2.0
qjpeg.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qjpeg.dll	5.11.2.0
qsvg.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qsvg.dll	5.11.2.0
qtga.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qtga.dll	5.11.2.0
qtiff.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qtiff.dll	5.11.2.0
qwbmp.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qwbmp.dll	5.11.2.0
qwebp.dll	C:\dev\jaero\JAERO-master\JAERO\release\imageformats\qwebp.dll	5.11.2.0
DWrite.dll	C:\Windows\System32\DWrite.dll	6.2.9200.22164
qgenericbearer.dll	C:\dev\jaero\JAERO-master\JAERO\release\bearer\qgenericbearer.dll	5.11.2.0
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	6.1.7600.16385
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	6.1.7601.17970
aeroambe.dll	C:\dev\jaero\JAERO-master\JAERO\release\aeroambe.dll	0.0.0.0
libmbe.dll	C:\dev\jaero\JAERO-master\JAERO\release\libmbe.dll	0.0.0.0
clbcatq.dll	C:\Windows\SysWOW64\clbcatq.dll	2001.12.8530.16385
devenum.dll	C:\Windows\SysWOW64\devenum.dll	6.6.7601.19091
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.1.7600.16385
Wldap32.dll	C:\Windows\SysWOW64\Wldap32.dll	6.1.7601.23889
wintrust.dll	C:\Windows\SysWOW64\wintrust.dll	6.1.7601.23971
msdmo.dll	C:\Windows\System32\msdmo.dll	6.6.7601.17514
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.1.7601.23471
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.1.7600.16385
RpcRtRemote.dll	C:\Windows\System32\RpcRtRemote.dll	6.1.7601.17514
BtMmHook.dll	C:\Program Files\WIDCOMM\Bluetooth Software\syswow64\BtMmHook.dll	6.5.1.4600
psapi.dll	C:\Windows\SysWOW64\psapi.dll	6.1.7600.16385
`

**Comment by KR0SIV** [comment]
I added the debug line as suggested to the application and run debug:

`.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
timeout --> closed
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
timeout --> closed
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
opening  "C:/Users/Harold/Google Drive/Inmarsat AREO Channels Attempt/JAERO 1/dev/audiolog_2018-12-04_20-15-51.ogg"
.`

**Comment by jontio** [comment]
`qDebug()<<data;` is bad as data is not a null terminated *char nor a QString. So that can cause unpredictable results like crashes.

The timeouts you got were normal. They mean the current Ogg file is closed due to the lack of data returning from libaeroambe. This usually happens when a C-channel finishes. so ...

```
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . timeout --> closed . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . timeout --> closed . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . opening "C:/Users/Harold/Google Drive/Inmarsat AREO Channels Attempt/JAERO 1/dev/audiolog_2018-12-04_20-15-51.ogg" 
```

the `.` mean the soundcard callback is being called normally as you added `qDebug()<<"."`, `timeout --> closed` means is closing the previous Ogg file, and ` opening "C:/Users/Harold/Google Drive/Inmarsat AREO Channels Attempt/JAERO 1/dev/audiolog_2018-12-04_20-15-51.ogg` means new audio data is coming in from libaeroambe and a new Ogg file as needed to save the audio to.

```
. aeroambe library loaded . opening "C:/Users/Harold/Google Drive/Inmarsat AREO Channels Attempt/JAERO 1/dev/audiolog_2018-12-04_20-17-03.ogg" . . . . . . . . . . . . . . . . . . . 20:17:24: Debugging has finished .
```

I'm not sure if the debugging finished here due to a crash or whether or not you stop it. either way the `.`s mean that audio out callback is being called.

I don't get any of the warnings you got when compiling `audiooutdevice.cpp` I am however probably using a slightly older compilers and you. I had a look through most of the the warnings but none of the ones I looked it should be a problem.

If you change the audio out callback to ...

```
qint64 AudioOutDevice::readData(char *data, qint64 maxlen)
{
    qint16 *ptr = reinterpret_cast<qint16 *>(data);
    int numofsamples=(maxlen/sizeof(qint16));

    for(int i=0;i<numofsamples;i++)
    {
        *ptr=qrand();
        ptr++;
    }
    return (numofsamples*sizeof(qint16));

}
```

then that should cause you to hear white noise if the libaeroable is loaded. you don't need any c-channel signal.

So far I have found one major bug in libaeroambe...

https://github.com/jontio/libaeroambe/commit/ba8a2e3ee658db46952705b522f6ca292bf0097a 

For this bug, it worked fine on Windows but in Linux that would crash with the segmentation fault. so there may be something similar to that still left in libaeroambe. That's why I prefer C++ and Qt so as to avoid mistakes like that.

Another test to do would be to temporarily disable the calling to the stuff in libaeroambe. This can be done by returning straight away from the following slot...

```
void AeroAMBE::to_decode_slot(const QByteArray &data)
{
    return;
}
```

If you get a segmentation fault after doing this should be a bug in JAERO.

**Comment by KR0SIV** [comment]
I tried what you've suggested.

changing the audiocallback did indeed output static/random audio. I then reverted that change and make the suggested change to AeroAMBE and ran it again in debug.

Unfortunately JAERO did segment fault after about 60 seconds.

![segfault](https://i.imgur.com/8vSVIYp.png)

**Comment by jontio** [comment]
On the positive that shows that at least JAERO can output audio.

krmaier found this bug in libaeroambe...

https://github.com/jontio/libaeroambe/issues/2

Which could cause a segmentation fault. however, as you put a dummy function in it should never have been called. Still you should probably update that just in case.

When making changes sometimes things can get muddled up so just to be safe it might be a good idea to clean any project that you have modified. On the command line it's `make clean` or `mingw32-make.exe clean` depending on how your system set up. For the two projects that you have open and Qt creator you can click `build->clean all`.

After you've done that you need to figure out at what point the segmentation fault happens. I haven't done it in Qt creator but have done it from the command line using the command `gdb` (you probably would need to install that with pacman). Then it's `target exec JAERO.exe` then `run`.

You probably don't need the `qDebug()<<".";` anymore as you know the function as being called.

**Comment by KR0SIV** [comment]
Fantastic!

I appears that the bug in libaeroambe was my issue. I recompiled everything and with the latest libaeroambe it's working perfectly as an x32 build.

Thanks so much for your help/support it's greatly appreciated.

**Comment by jontio** [comment]
That's good to hear. I am glad the problem was found.
