### ISSUE TITLE
Beep on C-Channel assignment message

### ISSUE THREAD

**Issue by acarslogger** [jontio/JAERO#34]
I'm running windows v1.0.4.8. Although in the Settings I have unchecked the 'Beep on multi line text message', with this latest release I getting a beep every time a C-Channel assignment message is received.
e.g. 10:30:59 12-12-18 AES:4A81F8 GES:90 Receive Freq: 1546.19 Global Beam Transmit 1647.69

Could you provide an option to disable the beep.
Thanks
Stuart

**Comment by jontio** [comment]
The beep for C-Channel assignment wasn't intended for release. I've removed it from the source so that will fix your problem. However I expect the next binary release I will do won't be until late January.

**Comment by acarslogger** [comment]
Thanks for the info. Looking forward to the next windows binary release.
Stuart

**Comment by jontio** [comment]
Released. All done.
