### ISSUE TITLE
Installing Jaero on Pi3

### ISSUE THREAD

**Issue by radiostationx** [jontio/JAERO#38]
Hi J,
Tried to follow your instructions 
[https://github.com/jontio/JAERO/wiki/c-band-on-pi](url)

The version listed has been deleted and repalced with version 1.0.4.10

`wget http://download.opensuse.org/repositories/home:/mnhauke:/sdr-devel/openSUSE_Leap_42.2_Ports/armv7hl/jaero-1.0.4.10-11.2.armv7hl.rpm`

When downloaded the next step was

`rpm2cpio jaero-1.0.4.10-11.2.armv7hl.rpm  | cpio -idmv`

I have a folder JAERO, inside this is bin and share.

The excecutable resides in bin (jaero)
`
But when I try to run the executable

jaero will not run.

Any help appreciated.

![jaero](https://user-images.githubusercontent.com/17929166/56473669-4515a900-6466-11e9-87ee-dcf1405d9e56.png)

**Comment by jontio** [comment]
That's an automatic build system that mnhauke runs and is targeted for opensuse. 

I'm not sure if there are any problems with the build system. There are other such as http://download.opensuse.org/repositories/home:/mnhauke:/sdr-devel/openSUSE_Leap_42.3_Ports/armv7hl/jaero-1.0.4.10-11.3.armv7hl.rpm , I'm not sure what the compatibility of any of the others are with the PI.

Personally I would compile JAERO from source for the PI as using something for opensuse on raspberrian seems problematic.

Currently I don't have time to investigate this problem as I have another project on my hands.

Cheers,
Jonti

**Comment by abcd567a** [comment]
## Tried to build deb package on RPI  from source code.

### ATTEMPT-1: qmake make (Failed)

```
sudo apt-get install qt5-qmake
sudo apt-get install qtbase5-dev
```
.
```
git clone https://github.com/jontio/JAERO.git

cd ~/JAERO
qmake make
qmake: could not find a Qt installation of ''

cd ~/JAERO/JAERO
qmake make
qmake: could not find a Qt installation of '' 
```
.

### ATTEMPT-2: dpkg-buildpackage -b (Failed)
```
sudo apt-get install build-essential dh-make 
```
.
```
cd /home/pi
git clone https://github.com/jontio/JAERO.git 
sudo cp -r /home/pi/JAERO/JAERO  /home/pi/jaero-1.0.4.10

cd /home/pi/cd jaero-1.0.4.10
sudo dh_make -s -c gpl -e myEmailAddress --createorig 

Email-Address       : myEmailAddress
License             : gpl2
Package Name        : jaero
Maintainer Name     : root
Version             : 1.0.4.10
Package Type        : single
Date                : Sat, 27 Apr 2019 20:22:52 -0400
Are the details correct? [Y/n/q]
Please respond with "yes" or "no" (or "y" or "n")
Currently there is not top level Makefile. This mayrequire additional tuning
Done. Please edit the files in the debian/ subdirectory now.

y

ls /home/pi/jaero-1.0.4.10/debian
changelog  jaero.cron.d.ex    manpage.1.ex     postinst.ex  README.Debian  watch.ex
compat     jaero.default.ex   manpage.sgml.ex  postrm.ex    README.source
control    jaero.doc-base.EX  manpage.xml.ex   preinst.ex   rules
copyright  jaero-docs.docs    menu.ex          prerm.ex     source

cd /home/pi/jaero-1.0.4.10
sudo dpkg-buildpackage -b

dpkg-buildpackage: info: source package jaero
dpkg-buildpackage: info: source version 1.0.4.10-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by root <myEmailAddress>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build jaero-1.0.4.10
 debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   dh_clean
 debian/rules build
dh build
   dh_testdir
   dh_update_autotools_config
   dh_auto_configure
        qmake -makefile -nocache "QMAKE_CFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" "QMAKE_CFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" "QMAKE_CXXFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" "QMAKE_CXXFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" QMAKE_LFLAGS_RELEASE=-Wl,-z,relro QMAKE_LFLAGS_DEBUG=-Wl,-z,relro QMAKE_STRIP=: PREFIX=/usr
Can't exec "qmake": No such file or directory at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 270.
dh_auto_configure: qmake -makefile -nocache QMAKE_CFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 QMAKE_CFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_RELEASE=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_DEBUG=-g -O2 -fdebug-prefix-map=/home/pi/jaero-1.0.4.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 QMAKE_LFLAGS_RELEASE=-Wl,-z,relro QMAKE_LFLAGS_DEBUG=-Wl,-z,relro QMAKE_STRIP=: PREFIX=/usr failed to to execute: No such file or directory
debian/rules:18: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by jontio** [comment]
qmake make shound be differend commands...

`qmake`

then after that

`make`

**Comment by abcd567a** [comment]
```
pi@raspberry:~/JAERO $ qmake
qmake: could not find a Qt installation of ''

pi@raspberry:~/JAERO $ cd JAERO
pi@raspberry:~/JAERO/JAERO $ qmake
qmake: could not find a Qt installation of ''

pi@raspberry:~/JAERO/JAERO $ make
make: *** No targets specified and no makefile found.  Stop.

pi@raspberry:~/JAERO/JAERO $ cd ..
pi@raspberry:~/JAERO $ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by jontio** [comment]
not too sure but try..

`sudo apt-get install qt5-default` 

then try and make a simple qt project to make sure you qt is working (google that) needs a pro file and a main.c file.

run `make clean` just incase

**Comment by abcd567a** [comment]
Prepared a test QT app as given here
https://www.linux.org/threads/c-tutorial-create-qt-applications-without-qtcreator.18409/

**Works OK**

![image](https://user-images.githubusercontent.com/28452511/56872048-bd461680-69f2-11e9-97dd-3199dd3d2424.png)


### Tried on JAERO, no luck.
```
pi@raspberry:~ $ cd JAERO/JAERO
pi@raspberry:~/JAERO/JAERO $ qmake  JAERO.pro
Project ERROR: Unknown module(s) in QT: multimedia svg
pi@raspberry:~/JAERO/JAERO $ make
make: *** No targets specified and no makefile found.  Stop.
pi@raspberry:~/JAERO/JAERO $ make clean
make: *** No rule to make target 'clean'.  Stop.

```

**Comment by jontio** [comment]
you will get a few things like this along the way. it says to install multimedia and svg.

try `apt-cache search qt | grep multimedia` etc to find the dev packages needed (also google them). 

there are others such as libcorrect so also have a look at
https://github.com/jontio/libaeroambe/wiki/Building_64-bit_binaries_for_Linux

again google these errors to tell you what packages you need to install. everything in either in the linux distro repo or on github.

**Comment by abcd567a** [comment]
Thanks Jontio for help, really appreciate. 

Kind of busy for next few days, will try your tips as soon as I find time.

**Comment by kevinelliott** [comment]
Hey guys, any update on this? I think it's still very difficult to run JAERO from Linux and Pi3/Pi4, and it would be fantastic if we could simplify this.

**Comment by radiostationx** [comment]
Hello Kevin,
We have Jaero working perfectly now with buster desktop on pi 3/4.
Please see my blog page for details
[https://www.merseyradar.co.uk/airband-radio/satellite-acars-reception-on-l-band-with-jaero/](url)
Specifically this list of commands
[https://docs.google.com/document/d/1IyH9eMeI2_CC2j0QYMHHrsV_ky_07WAJekJBjizzaLo/edit?usp=sharing](url)

Incidentally , I have another blog page with build details for DIY antenna designs that have worked very well
[https://www.merseyradar.co.uk/airband-radio/l-band-diy-antennas-for-jaero/](url)

**Comment by thebaldgeek** [comment]
For updated instructions to build Jaero on a Raspberry Pi 4, see my GitHub page here:     
[](https://thebaldgeek.github.io/jaero.html)     
    
I recommend using the PiSDR distro. [](https://github.com/luigifcruz/pisdr-image)   
     
Note, these instructions are for building from source Jaero v1.0.4.11. The latest version (March 2021) of Jaero uses a newer version of QT (5.12) which is very complicated to build (and takes around 4 hours). There are also errors for RaspberryOS Buster in the new version ci-linux-build.sh script that I was unable to debug after several hours.    
      
I could get around 5 instances of Jaero to run, more will run, but the decode rate drops off (and the Pi4 CPU was at 100%).

**Comment by jontio** [comment]
I have added a build script for the Pi. The process for a fresh Raspberrian OS (or other debian based) should be something like...

```
sudo apt install git
git clone https://github.com/jontio/JAERO
cd JAERO
./pi-build.sh
```

Do have a look through the pi build script ( https://github.com/jontio/JAERO/blob/master/pi-build.sh ) to make sure you're happy with what it does to your system.
