### ISSUE TITLE
Problem compiling libaerombe

### ISSUE THREAD

**Issue by a9e78rauijasdf** [jontio/JAERO#40]
Hey guys.

Im trying to compile JAERO, following the instructions on https://github.com/jontio/libaeroambe/wiki/Building_64-bit_binaries_for_Linux for Kubuntu 19.04 (i know - guide is for 18.04).

Im currently stuck on this error, when compiling libaerombe:

mbelib-master/test/test.cpp:1:10: fatal error: gtest/gtest.h: No such file or directory

Which I cannot find/resolve. I've also tried compiling Jaero with Qt Creator - this gets me stuck on "Unknown modules in QT: multimedia svg".

Not the easiest compile task I've seen ;) Any help/pointers..?

**Comment by jontio** [comment]
For missing dependencies I suggest using `apt-cache` and `apt-file`.

In this instance you're missing `gtest/gtest.h` so type ...

```bash
apt-file search gtest/gtest.h
```

for `Unknown modules in QT: multimedia svg` type...

```bash
apt-cache search libqt5 |grep module |grep  multimedia
```

and

```bash
apt-cache search libqt5 |grep  module |grep svg 
```

That should help to find the dependencies
