### ISSUE TITLE
Please, add LICENSE

### ISSUE THREAD

**Issue by afiskon** [jontio/JAERO#46]
Without a LICENSE file it's not clear under which license the source code is distributed. From what I know (I'm not a lawyer) in some countries you might be responsible for any harm that your software may do unless license says otherwise.

**Comment by jontio** [comment]
The problem I have is that I've added other 3rd partly libraries into my repo and they don't always have the same license as mine (e.g kissfft is BSD). I realize now that I shouldn't have done that but it made it easy to compile JAERO on Windows as you didn't need to find all the other libraries, now it's a bit of a hassle. Currently the repo is setup such that each folder has it's own license file; for JAERO it's license file is https://github.com/jontio/JAERO/blob/master/JAERO/LICENSE . Ultimately I would like to remove and unlink JAERO from expecting the other libs to be bundled with JAERO but I haven't done that.
