### ISSUE TITLE
JAERO crushing with libaeroambe

### ISSUE THREAD

**Issue by sv1** [jontio/JAERO#52]
Hello,

JAERO with libaeroambe is crushing as soon as it lock on the signal with error bellow:

./JAERO: symbol lookup error: /usr/lib/x86_64-linux-gnu/libaeroambe.so: undefined symbol: mbe_processAmbe4800x3600Frame

OS is linux

**Comment by jontio** [comment]
What is your setup?

Are you using the latest build ( https://github.com/jontio/JAERO/releases/tag/latest ) using the precompiled binaries or are you compiling it yourself?

If you're building it yourself have a look at https://github.com/jontio/JAERO/blob/master/ci-linux-build.sh to get an idea of how to compile libaeroambe and install it.

During putting together libaeroambe a pull request wasn't made into mbelib which was where it was forked from so unfortunately libaeroambe can't use the mbelib version that you might've obtained elsewhere as that version wont know about the specific AERO veriant of ambe. This is a bit of a problem, so as you can see in the ci-linux-build.sh I suggest statically linking the modified mbelib version with libaeroambe (but still building libaeroambe as a shared library) to avoid the problem of having two libraries with the same name. Although I haven't tried it I would think that this should work even if you have another shared version of mbelib on your system.

My guess is you have built and installed everything from source and/or you might've installed a version of mbelib that didn't understand the AERO variant or overwrote one that did with one that didn't.

Yes it is not the best situation but I am not going to figure out how to get the mbelib variant into where it was forked from which I think was probably https://github.com/szechyjs/mbelib . Ideally someone should do this though.
