### ISSUE TITLE
Update version of libacars.

### ISSUE THREAD

**Issue by thebaldgeek** [jontio/JAERO#53]
Libacars has undergone many improvements and updates.   
The quality of the messages decoded by Jaero would be greatly increased by using the latest version.

Thanks for your consideration.

**Comment by jontio** [comment]
I have noticed that there is a new version of libacars. I haven't really looked into it but I think the new API is different from the old one hence why I'm still using the old one. That would mean some changing around of the code in JAERO. Currently I don't have any time to do that. If someone else wants to do that, that would be greatly appreciated.

**Comment by slongani** [comment]
Hi Ben & Jonti,

Couple of weeks ago, I compiled JAERO using the latest pull of libacars. So far, it appears to be working normally for me (not sure if I am losing out on any decodes this way).

I did not use the ci-build-linux script, instead did a qmake/make after installing the dependencies. If you can tell me what compile errors you are getting, I can sort them out.

**Comment by elafargue** [comment]
Same here, jaero seems to work fine on the latest release (v2.1.3) with minimum tweaks since libacars is now called libacars-2
```
ldd JAERO | grep acars
	libacars-2.so.2 => /usr/local/lib/libacars-2.so.2 (0x00007f1342381000)
```

**Comment by thebaldgeek** [comment]
Myself and most of the users I help are running Jaero on Windows.
I have spent hours and hours trying to build Jaero on a Windows PC, but it is beyond my skill set.
Ideally it would help a LOT of people if we had a new Windows binary that used the latest libacars.

**Comment by jontio** [comment]
I've tried the latest commit to master of libacars on Linux seems to work but haven't really checked it. It builds and links fine. However where he puts the includes are a bit of a nuisance. He has libacars-2/libacars and all the files in that folder don't mention libacars-2. When creating the libacars package I could get rid of the whole libacars-2/libacars and turn it into libacars but that would clash if people wanted to use both versions so that doesn't seem like a good idea. On Linux using the header is pretty easy as I just have to put something like `INCLUDEPATH += /usr/local/include/libacars-2/` but on Windows that location will depend on where the person has installed msys2 to. I can't find anything in qmake that gives the system include part yet that actually works. In the meantime I've created a separate branch for the naming thing https://github.com/jontio/JAERO/tree/libacars2 . It has to work on Linux, Windows and Pi before any merge into the master. Most importantly it has to work with the git actions. Currently the branch only works for Linux and I haven't checked if it works for the Linux git action build.

**Comment by jontio** [comment]
QMAKE_INCDIR doesn't seem to output anything btw

**Comment by jontio** [comment]
```
for(var, $$list($$enumerate_vars())) {
    message($$var)
    message($$eval($$var))
}
```

In the pro files shows all the system variables that's a handy thing to rememeber, still looking through them. there are heaps of them.

**Comment by jontio** [comment]
First I tried ...

```
for(var, $$list($${QMAKE_DEFAULT_INCDIRS})) {
    inc_path_item=$$split(var,"/")
    inc_path_item_last_folder=$${member(inc_path_item,-1)}
    equals(inc_path_item_last_folder,"include") {
        new_inc_path_posibility=$$var"/libacars-2"
        message($$new_inc_path_posibility)
        INCLUDEPATH += $$new_inc_path_posibility
    }
}
```

terrible then a better solution...

```
for(var, $$list($${QMAKE_DEFAULT_INCDIRS})) {
    new_inc_path_posibility=$$files($${var}/libacars-2, false)
    !equals(new_inc_path_posibility,"") {
        message( "libacars-2 location is "$${new_inc_path_posibility} )
        INCLUDEPATH += $$new_inc_path_posibility
    }
}
```

**Comment by jontio** [comment]
Github has built has a pre release in the latest build that at least built correctly https://github.com/jontio/JAERO/tree/latest . I haven't tried them out. If you guys can put them through their paces that would be good. Just to let you know there was a mistake in the naming of the settings if using the `-s` option that I fixed. So if you use this version you will have to redo them but it had to be done.

**Comment by thebaldgeek** [comment]
Thanks so much for this Jonti. I will be checking it out as soon as I can.
Very excited about testing this. Been seeing many 'broken' messages from the new aircraft.

**Comment by elafargue** [comment]
Looking good on my end on Linux!

**Comment by thebaldgeek** [comment]
Hi Jonti.
Thanks for building the Windows binary.
Unfortunately I have some issues getting it to run (Note, currently I am running 1.0.4.11-73 dirty).
The first error is a missing libxml2-2.dll which I was able to find and download it and moved on to the next error.

`The procedure entry point DLLMain could not be located in the dynamic link library C:\Program Files\JAERO\libacars-2.dll`

At this point, I am not sure even what that error is telling me and what I should do.
Thanks.

Ben

**Comment by jontio** [comment]
Oh bother. Currently there is nothing that automatically scans the required shared libraries and instead I just figure out which ones are needed manually then input their names into the Windows build script. It looks like the new look libacars uses at least one new one. The reason you're getting the second error is you probably have the wrong libxml2-2.dll, you need the one that github used when building JAERO. I'll get the build script sorted out this today.

**Comment by thebaldgeek** [comment]
Most 'download dlls' websites only have either 32 or 64 bit libxml2-2, I have a 64 bit OS, so went with that one, but either way, thanks for sorting it. Really looking forward to this build, its got the new libacars and JSON (I use Node-RED) so super excited about it.

**Comment by jontio** [comment]
I saw your website a few months ago and started having a look into node red as I wondered how you did. As you may know pudding had bladder cancer so I use node red and one of the AI plug-ins to detect her and send me a push notification to my phone when she used the kitty litter tray as I need know when that happened to help her. Yeah it's heart breaking but it was very useful at the time.

I also mucked around with some websocks and rented a vm in the UK and put on node red, jaero, mosquitto, and a c++ app that would accept websockets as my c++ programming is better than javascript needed by node red. Then I used a zmq signal coming from europe to go into JAERO. I send everything to the mqtt broker...

![image](https://user-images.githubusercontent.com/13667843/142793467-60f4fcaf-12b4-417c-9856-5673f7e552ae.png)

I had to add the watchdog timer as the zmq signal would sometimes go down, I'm not sure why that is. I am just using one signal as I just test these things out not really use them. it can be extended to multiple signals it's just the bandwidth for zmq that is massive if you stream it over the net. I added a read only guest account to the mqtt broker if you or anyone want's to look.

```
Uri: jontio.mooo.com
Port: 8883
Username: guest
Password: a74qrP6x
Topic: jaero/#
```

I'll probably take it down sometime in the future as it's costing me but at the moment I really don't care. Anything that gets sent to the broker with topic jaero gets sent to the websocket server. I wrote a simple webpage with some javascript to connect to the server here  https://jontio.zapto.org/jaero_ws/  it's my take on what you did just to see if I could do it.

**Comment by jontio** [comment]
I added the two missing DLLs and on my Windows machine it seems to run. Hopefully that fixes everything https://github.com/jontio/JAERO/releases/tag/latest

**Comment by thebaldgeek** [comment]
Jonti.
This new build works great. Thanks again for adding libacars-2. The new aircraft with long messages was a real issue, now with the automatic message reassembly, its working great! (Plus all the bug fixes and updates in that package).

I was very humbled that you took a look at Node-RED. It has enabled me to sift the Jaero UDP data and put it into tables with very little code skills. I'm an electronics and systems guy and have never learned how to code, so it was a great tool for me to get started.
Now that we are 7 years in and the site has grown, its the wrong tool entirely, but its tough to throw it all away.

Your page/MQTT data flow is very cool. Thanks for the chance to take a look at it.

Cheers,
Ben.
