### ISSUE TITLE
Resolve hostname in UDP stream.

### ISSUE THREAD

**Issue by thebaldgeek** [jontio/JAERO#54]
In Settings -> ACARS window I would like to be able to add a hostname and port for data to be sent to.    
At the moment only lP:port function.     
Many people are running Jaero and feeding ACARS data to a central website. If the IP address changes all Jaeros need to be updated. Enabling Jaero to resolve the hostname would solve this issue.    
     
Thanks for your work.

**Comment by jontio** [comment]
Yup that would be a nice thing to have. I don't have time to do that at moment. If someone else wants to do that, that would be greatly appreciated.
