### ISSUE TITLE
BUG: pulseaudio starts using too much CPU and eventually crashes when running more, than 4 instances of JAERO

### ISSUE THREAD

**Issue by vladisslav2011** [jontio/JAERO#77]
Steps to reproduce:

1. Start 5 instances of JAERO:
```
for (( k=0;k<5;k++ )) ; do jaero & sleep 2 ; done
```
2. Enable audio output in every instance of JAERO if not enabled previously
3. Run `top` in another terminal window, to see pulseaudio CPU usage
4. Run `pavucontrol` or some more instances of JAERO to crash pulseaudio

Expected behavior:
pulseaudio consumes ~10...15% of CPU max
pulseaudio does not crash when starting `pavucontrol`

Observed behavior:
pulseaudio consumes 100% of CPU time (whole core) and even more
pulseaudio sometimes crashes when running `pavucontrol`

![JAERO-pulse-cpu-usage](https://user-images.githubusercontent.com/17007837/188338316-5569d186-d567-400c-9f69-9f321faea228.png)

**Comment by thebaldgeek** [comment]
This is a known issue and has nothing to do with Jaero.
I don't have time just now to search for the posts on it, but bottom line, kill pulse and use SDRReceiver being sure to turn off all sound / voice decode and beeps.
With zero sounds you can easily run 8 to 12 Jaeros on a Pi 4.

**Comment by vladisslav2011** [comment]
I know, that pulseaudio itself is a "known issue", but this issue can be fixed on JAERO side.
PR is ready https://github.com/jontio/JAERO/pull/79

**Comment by jontio** [comment]
I should have merged that into something else but it's in master.
