### ISSUE TITLE
Can't start decoding win/raspi JAERO

### ISSUE THREAD

**Issue by dcmk1mr2** [jontio/JAERO#81]
Getting: "Console disabled while raw demodulated data is routed to UDP port 8795 at LocalHost" 

Can't find .ini files in expected places. 

Thanks!

Martin
![no_start](https://user-images.githubusercontent.com/244156/188537124-d6ab0817-21b4-4635-9758-85cf2c091cd0.png)

**Comment by thebaldgeek** [comment]
Do you really want to decode the raw data? Thats not something most users want to do.... So Im just checking what you are looking to do.
if you just want to decode L-Band data (or C-Band if you have a dish), then just un-click the raw data icons:
![image](https://user-images.githubusercontent.com/7385116/188545768-2cc4e1ec-c355-4c9e-acba-fb41d2fce9a8.png)

This will then decode the messages in Jaero as I expect you are wanting to do.
